### PR TITLE
Step 1 completed

### PR DESCRIPTION
**Pull request by alesky78**
1 step is completed

this is the list of the change:

- For consistency rename genericServer.Connection to NetStringConnection
- Move Server.NetStringServerSocket to be a top-level class
- New class SOCInboundMessageQueue from Server.Treater, Server.inQueue and related methods

### CODE REVIEW

**Comment by alesky78** [comment]
Jeremy

I noted now that i didn't work in UTF-8 so all the 6 file commited are in cp1252

**Comment by jdmonin** [comment]
Hi Alessandro,

Based on imports and calls, it looks like maybe soc.server.SOCInboundMessageQueue should belong to the genericServer package to maintain the generic/SOC separation.

My main concern though is that besides the expected moves and renames which do the refactoring, this pull's SOCInboundMessageQueue also contains a big implementation change. The Server and Treater threads have always synchronized and blocked on the inQueue vector. In this pull that isn't done anymore, instead there is a polling and sleeping mechanism with ConcurrentLinkedQueue. I'm open to talking about that kind of change but it's too much at once for this kind of refactoring: Please restore the proven Vector synchronization.

For "paperwork", in the files you've changed or added please don't forget to credit yourself with an attribution comment, something like:

      * Portions of this file Copyright (C) 2016 Alessandro D'Ottavio

Also please remove the new @author tag from NetStringServerSocket: This class was moved, not newly designed and created.

Thank you for your patience with these details!
-Jeremy

**Comment by alesky78** [comment]
ok no problem with all the change, that is part of the collaboration.
I immagine also that this is probably  the the strategy that you use to keep tracking of the changes in the software. 
My change over the syncornization is hide inside the commits that i did. you are absolutely right...

well i this point to revert the syncornization... i will: 
- reintroduce in the Server class  the  method to put messge in the queue... like the old process method Server.treat(msg, stringConnection);
- remove the references from the Connection objects wiht the InboundMessageQueue becuse they will call Server.treat(msg, stringConnection);
- in this way i will syncornize the code over the IboundMessageQueue only in the Server class has before was over the Vector

this should revert exactly the same logic as before

anyway if you agree wiht the refactoring over the syncornize logic... I can open another ticket and we can discuss there this kinds of topic.

**Comment by jdmonin** [comment]
Thanks again, those look great so far. Once the inQueue revert is ready, I'll be happy to merge.

**Comment by alesky78** [comment]
Hi Jeremy

i reverted the code, now the sync logic is the same as before...
i tested the changes in both pratics and real network mode

**Comment by jdmonin** [comment]
Hi Alessandro,

Thanks again for following up so quickly with those details!

This is now merged. I have some followup commits with minor adjustments to keep some parts that were overlooked and to fit the project coding style.

Thank you again!
-Jeremy

**Pull request merged**
